version: '3.8'

  
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQL4
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="Str0ngP@sSw0rd !"
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
      - MSSQL_MEMORY_LIMIT_MB=2048
    ports:
      - 1436:1433
    volumes:
      - /SQLdata:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Str0ngP@sSw0rd !' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
