# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/mssql/server:2022-latest
ENV MSSQL_PID=Enterprise
ENV MSSQL_AGENT_ENABLED=true
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD="Str0ngP@sSw0rd !"


RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]